### ISSUE TITLE
Social Media Page Border Increase

### ISSUE THREAD

**Issue by fed-tech** [fed-tech/FED-Frontend#223]
### Issue Summary

UI Enhancement

### Issue Description

The middle box border on the Social Media page needs to be increased for better visibility.

![image](https://github.com/user-attachments/assets/3297d76a-6ad2-4ecf-b0dc-f67165371962)

### Priority

Medium - Should be addressed soon

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [X] Design
- [ ] Other

**Comment by yashsirola9410** [comment]
After investigating the problem thoroughly, I have come to the conclusion that this issue cannot be manually modified within the file, as the content is imported from an external source. This import process seems to be central to the issue, which restricts direct changes to the file. I am currently looking into alternative solutions to address this.

"The provided <div> HTML snippet has the class "rsme-embed rsme-instagram-embed 379da88d-c032-42d6-a60b-9324b3267c12".
This <div> does not seem to be explicitly defined in the Social component code above, but it's likely dynamically generated by the SocialEmbed component or an external library used within it."

**Comment by fed-tech** [comment]
@AnshRaj112 kindly look into the issue and resolve the queries that @yashsirola9410 is facing.

**Comment by fed-tech** [comment]
@AnshRaj112 @yashsirola9410 give its update by tomorrow eod.
