### ISSUE TITLE
 Social Media Page Alignment Issue

### ISSUE THREAD

**Issue by fed-tech** [fed-tech/FED-Frontend#233]
### Issue Summary

UI/UX

### Issue Description

 The alignment of "FED" on the Social Media page is incorrect on both mobile and Windows views and needs fixing.

### Priority

Medium - Should be addressed soon

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [X] Design
- [ ] Other

### Additional Context (Optional)

![image](https://github.com/user-attachments/assets/b32fd187-5d05-4003-8017-58bc630ae791)

**Comment by Shubham-senger** [comment]
is it still open? 
If yes pls assign it to me 😊
