### ISSUE TITLE
Social Media Page Font Mismatch

### ISSUE THREAD

**Issue by fed-tech** [fed-tech/FED-Frontend#234]
### Issue Summary

UI/UX

### Issue Description

The font of "FED" on the Social Media page is different and needs to be standardized.

### Priority

Medium - Should be addressed soon

### Category

- [ ] Enhancement
- [ ] Refactor
- [ ] Security
- [X] Design
- [ ] Other

### Additional Context (Optional)

![image](https://github.com/user-attachments/assets/56287926-7f52-42a6-a9e2-7015123d1332)

**Comment by Shubham-senger** [comment]
I would love to work on this issue pls assign it to me
