### ISSUE TITLE
Testimonial Read More Issue in Mobile

### ISSUE THREAD

**Issue by fed-tech** [fed-tech/FED-Frontend#235]
### Bug Summary

 In mobile view, the "Read More" button for testimonials is not in the correct place. (Check for scrolling as well)

### Screenshots/Logs

![image](https://github.com/user-attachments/assets/ce1d21b0-5b8f-4d61-800c-38ea7ee12f03)

### Affected Browsers

Firefox, Chrome, Safari, Microsoft Edge

**Comment by fed-tech** [comment]
@yashsirola9410 whts ur update on this issue? We have seen you have closed the assigned issue without raising any PR. Its not a good practice to follow, the deadline is already passed. Kindly generate the req. PR by 23rd, make sure to keep ur branch updated with the base branch.

**Comment by yashsirola9410** [comment]
I pushed the code, but I don't know why it is not showing. I'll look into it.

**Comment by yashsirola9410** [comment]
![Screenshot 2024-12-22 234827](https://github.com/user-attachments/assets/7e7a3fb3-3ba9-4f2f-aa26-a8d0e3c28dd2)
updated  ^

and previous 
![Screenshot 2024-12-22 235028](https://github.com/user-attachments/assets/a0fefd3c-8ccd-482b-9a72-1fb7d9eb9875)
